# https://github.com/marketplace/actions/labeler
---
"scope: project":
  - ./*
"scope: docker":
  - Dockerfile
  - .dockerignore
"scope: shell":
  - ./*.sh
"scope: make":
  - Makefile
"scope: ci":
  - .github/**/*
